[package]
name = "chiprs-sdl"
version = "0.1.0"
authors = ["Paweł Marczewski <pwmarcz@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = "0.32.0-beta.2"
chiprs = { path = "../chiprs" }

[[bin]]
name = "chiprs-sdl"
path = "src/main.rs"
